### ISSUE TITLE
Oracle L2

### ISSUE THREAD

**Issue by mobxxx1** [SphinxShield/Audit-Reports#1]
The team have failed to build trust in their product with their investors by allowing their investors to lose their funds due to negligence and have ultimately failed. The auditor of the project should be more thorough in their approach towards such projects. 

The project has failed on all levels to protect their investors

**Comment by SphinxShield** [comment]
Dear mobxxx1,

We appreciate your concerns and take them seriously. As SphinxShield, we understand the importance of building trust in the crypto space, and we want to clarify our role as a smart contract auditor.

Our primary responsibility is to assess the security of smart contract codes. While we thoroughly evaluate the codebase for vulnerabilities, we do not involve ourselves in the development, marketing, or community management aspects of projects we audit. Consequently, we do not assume responsibility for the overall success or failure of a project.

In the case of the mentioned project, it's important to note that SphinxShield provided a smart contract code security audit exclusively. We did not engage in KYC or offer any other services for this project beyond our core expertise.

To address concerns about investor protection, we are committed to enhancing our services. In our upcoming V2 website, we will introduce analytics trackers, community scanning, and real-time alerts. This initiative aims to empower investors with valuable information, allowing them to exercise caution when a project deviates from its planned development or reaches a critical point. Our V2 app, inspired by Certik with additional features, will serve as a comprehensive tool for monitoring project health.

We take your feedback seriously, and rest assured, we will continue to assess and refine our processes to better serve the community and uphold the integrity of the projects we audit.

Thank you for your understanding.
